spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #initialization-mode: always
    #schema: schema.sql
    #data: data.sql
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    show-sql: true
    init:
      mode: always
      #data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    #show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      #ddl-auto: create-drop
    #properties:
    #  hibernate:
    #    format_sql: true



